


GET http://localhost:3000/users/donations/?id=67a78aa4c2b6708e34cac69b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtldmFsZzE5NTBAZ21haWwuY29tIiwiX2lkIjoiNjdhNzhhMTg3YzcwMmJjNWE5NjdiZTFmIiwiaWF0IjoxNzM5MjAzNjk2LCJleHAiOjE3MzkyOTAwOTZ9.E1P0nPEF-NJ8WLzcVdCPcp0KM2cRKcwNb9PxstrbBKA

//GET /api/users/:id/contributions → Get user contribution details
GET http://localhost:3000/users/contribution-info/?id=67a78aa4c2b6708e34cac69b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtldmFsZzE5NTBAZ21haWwuY29tIiwiX2lkIjoiNjdhNzhhMTg3YzcwMmJjNWE5NjdiZTFmIiwiaWF0IjoxNzM5MjAzNjk2LCJleHAiOjE3MzkyOTAwOTZ9.E1P0nPEF-NJ8WLzcVdCPcp0KM2cRKcwNb9PxstrbBKA

//GET /api/users/:id/activity-logs → Get user activity logs
GET http://localhost:3000/users/activity-logs/?id=67a78a187c702bc5a967be1f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtldmFsZzE5NTBAZ21haWwuY29tIiwiX2lkIjoiNjdhNzhhMTg3YzcwMmJjNWE5NjdiZTFmIiwiaWF0IjoxNzM5MjAzNjk2LCJleHAiOjE3MzkyOTAwOTZ9.E1P0nPEF-NJ8WLzcVdCPcp0KM2cRKcwNb9PxstrbBKA

//DELETE /api/users/:id → Delete user account (Admin)
DELETE http://localhost:3000/users/?id=67a78be5c2b6708e34cac6a1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtldmFsZzE5NTBAZ21haWwuY29tIiwiX2lkIjoiNjdhNzhhMTg3YzcwMmJjNWE5NjdiZTFmIiwiaWF0IjoxNzM5MjAzNjk2LCJleHAiOjE3MzkyOTAwOTZ9.E1P0nPEF-NJ8WLzcVdCPcp0KM2cRKcwNb9PxstrbBKA

{
    "reason":"Power"
}
